matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '8'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script: npm run prod-mac
deploy:
  provider: releases
  api_key:
    secure: YOP0xKFv21eh89zZq0LLqAMcrr8NoyxIf9WqFU6wDPFLrFLHATiZKosM0V9qXcGSfwY6yPGYYV1MMDnVAZ3xaMMFnjIDXita5rLGa77AUxR4R4yPV4AvoH0hx5kgrm8fmd7pZWBiJ13Ld0KVAHo0W1gUYiKoMG16XTfOAPfy0KudBdb7E7B50HScyBGAYzgz/WmOVn6QUcVA7KtvfIk5GPENp9fUfUBsRfC21hfXjNILhR8l5HMCbnMLo2rxs1EidnHe4Z5cybn6xOZf8KAhfYz9gHcqPNqAYQwDPLAXESAE23N4bGFPLOLS5cqdlnuB1HtJmTg5YLMPLDEugACRCgF6r1r+TLNAl82Th97HKskNUU/Kc9yyEgVpgMMX3hWLsSR365dtPp4G0X2NT8aIBi8P/fz/JDJkK4OnZffcLfFIDHxFsq8QiusFPawr5TBElfZ7lrj05JXVCIENoeUJWnevbiY/HVshuoTOhC8VkQLST5LltxBoX7ILN5GqAsN+n2pzzFANhWrsvtzqZrCMM2VS9KDgewreUhMOLV5G8qrqeunhL7vStvZIxxtzDicyAbReGGhn//DPRkKBju2/IJpkaqEBIXl397gb1HK6ThHef8kNo54LfLySR4zTnhb/kTLKOti7ur/30IvDUVXW18wVbfkZrbVShxzJI2zaqDU=
  file: ''
  on:
    repo: easemob/sdkdemoapp_windows
    branch: true
